
Turn 3
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 139, in <module>
    handleShipAI(ship)
  File "MyBot.py", line 76, in handleShipAI
    ships_priority.remove(ship.id)
ValueError: list.remove(x): x not in list

