
Turn 4
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 167, in <module>
    ships.remove(me.get_ship(id))
ValueError: list.remove(x): x not in list

