
Turn 4
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot.py", line 168, in <module>
    handleShipAI(me.get_ship(id))
  File "MyBot.py", line 102, in handleShipAI
    grid = wrapper.HaliteGrid(game_map,ship,unsafe_positions)
  File "D:\Python-Workspace\Halite\Trabalho-IA\choi_yena\utils_\wrapper.py", line 26, in __init__
    self.grid = self.convertMap(game_map)
  File "D:\Python-Workspace\Halite\Trabalho-IA\choi_yena\utils_\wrapper.py", line 43, in convertMap
    cellsCol.append(Cell(position.x, position.y, (position.x, position.y) in self.unsafe_positions, mapCell.halite_amount))
  File "D:\Python-Workspace\Halite\Trabalho-IA\choi_yena\hlt\positionals.py", line 113, in __eq__
    return self.x == other.x and self.y == other.y
AttributeError: 'tuple' object has no attribute 'x'

